# Generated by Django 3.1.2 on 2021-08-12 12:05
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    
    
