# Generated by Django 3.1.2 on 2021-08-12 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_type', models.CharField(blank=True, max_length=10, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('per_night', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'hotels',
                'managed': True,
            },
        ),
       
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.DecimalField(decimal_places=0, max_digits=1, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('makkah_days_1', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('madina_days', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('ziyarat', models.BooleanField(blank=True, null=True)),
                ('food', models.FloatField(blank=True, null=True)),
                ('makkah_days_2', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_ID', to='Customer.hotels')),
                ('hotel_madina', models.ForeignKey(blank=True, db_column='hotel_madina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_madina', to='Customer.hotels')),
            ],
            options={
                'db_table': 'packages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('pass_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('depart_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('depart_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('depart_origin_1', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_origin_1', models.CharField(blank=True, max_length=50, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Customer.packages')),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
    ]
